networks:
  network:
    name: ${PROJECT_NAME}-network

volumes:
  db-data:
    name: ${PROJECT_NAME}-db-data
  redis-data:
    name: ${PROJECT_NAME}-redis-data
  rabbitmq-data:
    name: ${PROJECT_NAME}-rabbitmq-data

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    image: ${REGISTRY}/nginx:${CI_COMMIT_TAG:-latest}

  db:
    extends:
      file: docker-compose.yml
      service: db

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq

  asgi:
    extends:
      file: docker-compose.yml
      service: asgi
    image: ${REGISTRY}/asgi:${CI_COMMIT_TAG:-latest}

  celery-worker:
    extends:
      file: docker-compose.yml
      service: celery-worker
    image: ${REGISTRY}/worker:${CI_COMMIT_TAG:-latest}

  celery-beat:
    extends:
      file: docker-compose.yml
      service: celery-beat
    image: ${REGISTRY}/beat:${CI_COMMIT_TAG:-latest}
